name: GitHub-Action-FT-Integration-QA
on:
  workflow_dispatch:
    inputs:
      testsToRun:
        description: 'Tests to run (from OpenText SDP/SDM)'
        required: true
        default: '...'
      suiteRunId:
        description: 'Suite Run Id (from OpenText SDP/SDM)'
        required: true
        default: '0'
      executionId:
        description: 'Execution Id (from OpenText SDP/SDM)'
        required: true
        default: '0'
      suiteId:
        description: 'Suite Id (from OpenText SDP/SDM)'
        required: true
        default: '0'    
  push:
    branches:
      - secondary
permissions:
  actions: write  # Explicitly grant actions:read for this workflow
  contents: read  # Retain read access to contents if needed
env: 
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    ACTIONS_STEP_DEBUG: true  # Enables debug logging
jobs:
  ft_integration_job:
    runs-on: [self-hosted, onprem]
    name: Integration-Job
    steps:
      # - name: Log workflow inputs for Octane
        # run: |
          # $inputs = ConvertFrom-Json -InputObject '${{ toJson(github.event.inputs) }}'
          # Write-Host "execution_parameter:: $($inputs | ConvertTo-Json -Compress)"

      - name: GitHub Action FT Integration
        uses: opentext/github-action-ft-integration-mbt@main
        id: gha-ft-integration
        with:
          octaneUrl: 'https://nadav-2.almoctane.com'
          octaneSharedSpace: 1001
          octaneWorkspace: 1003
          octaneClientId: ${{secrets.OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          minSyncInterval: 2
          logLevel: 2          
